[build]
command = """
  rm -rf .next node_modules/.cache && \
  pnpm run prebuild && \
  NODE_OPTIONS='--max-old-space-size=4096' pnpm run build
"""
publish = ".next"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_VERSION = "18.x"
VERCEL_FORCE_NO_BUILD_CACHE = "1"  # 关键修复项
